### ISSUE TITLE
Bug: 检测ansi支持

### ISSUE THREAD

**Issue by Bluemangoo** [BHznJNs/Calculator.rs#7]
有些控制台不支持ansi，你需要在不支持的时候把它禁用了。

如果你不想这样的话：

```text
Calculator.rs 1.8.4
> 1 + 1
= [0;93m2[0m
>
```

what you need:
```rust
 match enable_ansi_support::enable_ansi_support(){
    OK()=>{//code with ansi},
    Err()=>{//code without ansi}
}
```

**Comment by BHznJNs** [comment]
@Bluemangoo 能否给几个不支持 ansi 的终端的例子以方便测试？最好是 Windows 上可以使用的

**Comment by Bluemangoo** [comment]
cmd win7/10

**Comment by BHznJNs** [comment]
那行吧，win7/10 上的 cmd 我好像也装不了，[crossterm](https://github.com/crossterm-rs/crossterm) 貌似是能兼容 win7 的，我之后还是切换到 crossterm 把

**Comment by Bluemangoo** [comment]
你是win11吧，你可以试试11的cmd有没有。我的win11不在边上（人在学校）

**Comment by Bluemangoo** [comment]
你看看这里：
https://github.com/crossterm-rs/crossterm/blob/dfc67e54c8cde921d32c1392f6ed28fc14ac541e/README.md?plain=1#LL44-L45

它的支持还是用的ansi，所以还是会出错。

**Comment by BHznJNs** [comment]
主要有个问题，如果终端不支持 ansi 的话，要检测出来还是有些困难。

**Comment by Bluemangoo** [comment]
> 有些控制台不支持ansi，你需要在不支持的时候把它禁用了。
> 
> 如果你不想这样的话：
> 
> ```
> Calculator.rs 1.8.4
> > 1 + 1
> = �[0;93m2�[0m
> >
> ```
> 
> what you need:
> 
> ```rust
>  match enable_ansi_support::enable_ansi_support(){
>     OK()=>{//code with ansi},
>     Err()=>{//code without ansi}
> }
> ```

@BHznJNs

**Comment by BHznJNs** [comment]
Alright!

Note:
```rust
/// Checks if the current terminal supports ANSI escape sequences
/// return bool
crossterm::ansi_support::supports_ansi();
```

**Comment by Bluemangoo** [comment]
为了一个功能引入一个包不太好吧。

有原生的尽量直接用吧。

**Comment by BHznJNs** [comment]
@Bluemangoo 也不是为了这一个功能。
我正在写 repl 下输入时的语法高亮，为了这个功能，需要这个库的 enable_raw_mode 。正好 crossterm 也有类似的功能，就不多引入一个库了。
